### ISSUE TITLE
model ncf 中的NCF_input.py 中第40行逻辑是否有问题？

### ISSUE THREAD

**Issue by mathlf2015** [princewen/tensorflow_practice#1]
for i in range(len(full_data)):
        u = full_data['user'][i]
        t = full_data['user'][i]
应该改成
for i in range(len(full_data)):
        u = full_data['user'][i]
        t = full_data['item'][i]

第33,35行是不是没有意义
full_data['item'] = full_data['item'].map(lambda x:item_map[x])

item_set = set(full_data.item.unique())

**Comment by chongfaqin** [comment]
我看到这里，感觉应该是item

**Comment by princewen** [comment]
是的，谢谢

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
