### ISSUE TITLE
实验楼邀请您参与python/机器学习课程制作

### ISSUE THREAD

**Issue by markiremenber** [princewen/tensorflow_practice#10]
princewen，您好
     我是实验楼在线教育网站的课程运营何宇恒，在Github上看到您的python/机器学习项目，感觉该项目写得非常棒，也很能体现您在该领域的水平。实验楼现想邀请您成为实验楼的课程作者，利用业余时间制作该领域的相关课程内容。您是否有兴趣参与呢？希望能得到您的回复，非常感谢！

实验楼简介：实验楼是一家将Linux环境搬上网站，结合实验文档让学生一步步动手实践的培训网站，完全不同于枯燥的视频培训。如果您想了解的话，欢迎访问哟。
实验楼网址：www.shiyanlou.com
欢迎实验楼课程合作微信号了解详情：shiyanloukecheng

**Comment by princewen** [comment]
先找工作哈
