### ISSUE TITLE
运行错误，求帮助

### ISSUE THREAD

**Issue by yumh** [princewen/tensorflow_practice#11]
在RL/Basic-DRQN-Demo/DRQN.py 中，下面三行报错。
from helper import updateTargetGraph,updateTarget,processState,saveToCenter
from gridworld import gameEnv
# partial设置为True环境为部分可观测，如果设置为False，则是完全可观测
env = gameEnv(partial=True,Size = 9)

**Comment by Ontheroad123** [comment]
报的什么错
