### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by hujuan940506** [princewen/tensorflow_practice#4]
我运行Basic-PNN-Demo/main.py出现如下错误：

y_train_pnn, y_test_pnn = run_base_model_pnn(dfTrain, dfTest, folds, pnn_params)
TypeError: 'NoneType' object is not iterable

望大佬解答

**Comment by leejy2006** [comment]
the same error , wish to get answer

**Comment by leejy2006** [comment]
> 我运行Basic-PNN-Demo/main.py出现如下错误：
> 
> y_train_pnn, y_test_pnn = run_base_model_pnn(dfTrain, dfTest, folds, pnn_params)
> TypeError: 'NoneType' object is not iterable
> 
> 望大佬解答

你的问题解决了吗
