### ISSUE TITLE
关于ncf

### ISSUE THREAD

**Issue by liheyong** [princewen/tensorflow_practice#47]
您好，您的代码的GMF和MLP融合的时候，concat(gmf,mlp)这部分，gmf的列是embdding_size,mlp的列维度是embdding_size/2.为什么要这样设置呢，直觉上应该是列的维度一致才可以，请指教一下。谢谢。

**Comment by kruskr** [comment]
@liheyong 之前有个user_emb，item_emb的concat，下一层的emb扩展了2倍

**Comment by liheyong** [comment]
好滴
