### ISSUE TITLE
训练集验证集结果差别大

### ISSUE THREAD

**Issue by hujuan940506** [princewen/tensorflow_practice#5]
非常感谢作者的分享
我在用recommendation/Basic-DeepFM-model算法的时候，随着训练迭代次数的增加，train-result的分数越来越高，可以到92，而valid-result的分数越来越低，低至50 。跪求各位大佬的解答

**Comment by liangjingping123** [comment]
@hujuan940506 你也是在搞推荐系统吗?可以互相学习一下吗?我的微信号123870581....可以交流一下吗?

**Comment by hujuan940506** [comment]
@liangjingping123 大佬，我只是个小菜啊，你是主要做推荐系统的吗

**Comment by princewen** [comment]
加我微信吧，咱们加群一起交流 sxw2251
