### ISSUE TITLE
DKN中数据预处理，TransE.cpp无法运行

### ISSUE THREAD

**Issue by wyljpn** [princewen/tensorflow_practice#56]
运行TransE.cpp时出现了一个又一个问题，还是解决不了。
能不能上传一下"TransE_relation2vec_" + dim+ ".vec"和"TransE_entity2vec_" + dim + ".vec"？

**Comment by shelly1996** [comment]
> 运行TransE.cpp时出现了一个又一个问题，还是解决不了。
> 能不能上传一下“TransE_relation2vec_” +暗+ “.vec ”和“ TransE_entity2vec_” +暗+ “.vec”？

请问您解决了这个问题吗

**Comment by wyljpn** [comment]
> > 运行TransE.cpp时出现了一个又一个问题，还是解决不了。
> > 能不能上传一下“TransE_relation2vec_” +暗+ “.vec ”和“ TransE_entity2vec_” +暗+ “.vec”？
> 
> 请问您解决了这个问题吗

不好意思，过去太久了，已经忘记这件事情的结果了。。。
